quarkus.http.port=8081

quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=abhijitsen
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/amex_payments

quarkus.flyway.migrate-at-start=true

quarkus.log.category."com.amex.payments".level=DEBUG

quarkus.rest-client.truelayer-auth.url=${truelayer.auth-url}
quarkus.rest-client.truelayer-payments.url=${truelayer.base-url}

truelayer.base-url=https://api.truelayer-sandbox.com
truelayer.auth-url=https://auth.truelayer-sandbox.com
truelayer.client-id=${TRUELAYER_CLIENT_ID}
truelayer.client-secret=${TRUELAYER_CLIENT_SECRET}
truelayer.merchant-account-id=${TRUELAYER_MERCHANT_ACCOUNT_ID}
truelayer.signing-key-id=${TRUELAYER_SIGNING_KEY_ID}
truelayer.private-key-path=${TRUELAYER_PRIVATE_KEY_PATH}
truelayer.redirect-uri=https://your-ui.example.com/payments/callback
truelayer.webhook-uri=https://your-ngrok-url.ngrok.io/webhooks/truelayer
truelayer.beneficiary-name=American Express
truelayer.beneficiary-iban=DE89370400440532013000